[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "ssh_rsync_windows"
authors = [{name = "RoyOelen", email = "r.oelen@umcg"}]
dynamic = ["version", "description"]
